### ISSUE TITLE
invalid value in data

### ISSUE THREAD

**Issue by csae8092** [gfranzini/digEds_cat#165]
value: "1 (some)" is invalid according to the catalogue's  data(base)scheme since
(see: https://github.com/gfranzini/digEds_cat/wiki/Contribute#images) 
therefore the sync-function (https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/sync) does currently not work

**Comment by gfranzini** [comment]
Replaced (some) with 0.5 but the server 500 error is still there when syncing.
