### ISSUE TITLE
change url to web app

### ISSUE THREAD

**Issue by csae8092** [gfranzini/digEds_cat#223]
Please change the URL in the "Description" section of this repository's start page from
https://dig-ed-cat.eos.arz.oeaw.ac.at/
to
https://dig-ed-cat.acdh.oeaw.ac.at
Thank you!

**Comment by gfranzini** [comment]
Done!

**Comment by csae8092** [comment]
this is some response time!

**Comment by gfranzini** [comment]
:-D
