### ISSUE TITLE
Studia: http://www.morethanbooks.eu/atlas-de-datos-digital-editions-spanish/

### ISSUE THREAD

**Issue by gfranzini** [gfranzini/digEds_cat#242]

**Comment by csae8092** [comment]
any intention of merging the data?

**Comment by gfranzini** [comment]
I found this yesterday and wanted to study it today before I email the creator about it. I remember speaking to him at the TEI conference, where he told me he was compiling a list of Spanish projects. Guess this is the result! :)

**Comment by gfranzini** [comment]
But yes, I'd like to merge.
