### ISSUE TITLE
URLs must start with http....

### ISSUE THREAD

**Issue by csae8092** [gfranzini/digEds_cat#264]
URLs need to start with http otherwise the links from a catalog entry to the actual edition does not work (e.g. https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/232). This could be fixed in the application by applying some sanity checks but I think it is cleaner to fix this on data level.

**Comment by gfranzini** [comment]
OK, noted. This was a user-contribution. I'll double check next time.

**Comment by gfranzini** [comment]
Project 232 was the only instance of this error.
