### ISSUE TITLE
Inclusion criteria

### ISSUE THREAD

**Issue by nemobis** [gfranzini/digEds_cat#270]
Hello, I found this from http://dhawards.org/dhawards2016/voting/ and I read https://dig-ed-cat.acdh.oeaw.ac.at/documentation/ but I don't understand what the inclusion criteria are. Is this about annotated texts only? For instance, I suppose you wouldn't add all Wikisource transcriptions/ebooks to your catalogue, but I don't know what definition of "digital edition" you're using so I cannot tell for sure.

**Comment by gfranzini** [comment]
Hi, thank you for your question! I will add it to the FAQ section of the website to help future users.

The project is constantly evolving as users request more features and development on the app moves forward. At the moment we don't accept ebooks, any form of commercial digital books, or transcriptions made available via wikisource but projects whose authorship can be traced back to one or multiple individuals with an institutional affiliation (university of GLAM institution), if possible. We primarily look for digital editions and digital scholarly editions (by which we mean editions with a strong critical component) but people are also beginning to submit digital archives, textual collections where some texts are treated in more detail, etc. 

It's worth noting that people define their projects in various ways (random example: a project may define itself as a database when it fact it might be more of a digital archive) using different terms synonymously. This makes it difficult to pick what should be included in our list or not. The line of inclusion in our catalogue is a little blurry but I guess it reflects the fuzziness that comes with these projects.

If you have a project to submit but are unsure about its eligibility for inclusion, feel free to add it to this GitHub repository as an issue with the 'POTENTIAL' label and we'll take a look. [On our wiki](https://github.com/gfranzini/digEds_cat/wiki/Not-applicable) you find a list of projects we looked at but decided not to include.

**Comment by nemobis** [comment]
Thank you for the clarification. I understand that what we call an 
"edizione critica" in Italian is closer to what you have in mind, and 
that any digitisation which only has OCR is generally out of scope even 
if provided by an academic entity, right?

**Comment by gfranzini** [comment]
Esatto :-)
