### ISSUE TITLE
URLs should start with http

### ISSUE THREAD

**Issue by csae8092** [gfranzini/digEds_cat#286]
Ideally every URL in the data should start which a proper protocol (http, https) because if this is not the case, it could lead to unwanted side-effects like here: 
[https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/249](https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/249) -> clicking on the link behind Facultad de Filosofía y Letras Universidad Nacional Autónoma de México (UNAM) -> leads to [https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/www.filos.unam.mx](https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/www.filos.unam.mx) a page which obvisouly does not exist (though the good point is, that we can see the Dig-Ed-Cat).

I could implement a fix in the web page, but I'd prefer valid data instead

**Comment by gfranzini** [comment]
Fixed!
