### ISSUE TITLE
institution data inconsistency 

### ISSUE THREAD

**Issue by csae8092** [gfranzini/digEds_cat#288]
Institutions mentioned in Repository of Source Material(s) are hardly described in [institutions_places_enriched.csv](https://github.com/gfranzini/digEds_cat/blob/master/institutions_places_enriched.csv). See e.g https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/10 
also look at Leipzig University Library vs Library of the University of Leipzig

**Comment by gfranzini** [comment]
Thanks for flagging this up, will fix it.

**Comment by gfranzini** [comment]
All done.
