### ISSUE TITLE
Broken link(s) to old URL of digEds_cat

### ISSUE THREAD

**Issue by cthomasdta** [gfranzini/digEds_cat#320]
https://github.com/gfranzini/digEds_cat/blob/master/CONTRIBUTING.md:
> It's important you're consistent and follow these guidelines for the web application to display your contribution correctly.

= "web application" links to https://dig-ed-cat.eos.arz.oeaw.ac.at/, which is not active any more.

Possibly more URLs of that kind, appearantly replacing "dig-ed-cat.eos.arz.oeaw.ac.at" with "dig-ed-cat.acdh.oeaw.ac.at" will do the trick.

**Comment by gfranzini** [comment]
Ah, thank you so much for reporting the bug! I'll fix it. :-)
